import turtle
turtle.bgcolor("black")
wt=turtle.Screen()
tr=turtle.Turtle()

move=1
tr.speed(0)

for i in range(360):
    tr.write("welcome","false","center",font=("Showcardgothic",50))
    tr.penup()
    tr.goto(-200,100)
    tr.pendown()
    tr.color('orange')
    tr.right(move)
    tr.forward(100)
    tr.penup()
    tr.color('white')
    tr.pendown()
    tr.right(30)
    tr.forward(60)
    tr.pendown()
    tr.color('light green')
    tr.left(10)
    tr.forward(50)
    tr.right(70)
    tr.penup()
    tr.pendown()
    tr.color('light blue')
    tr.forward(50)
    tr.color('light green')
    tr.penup()
    tr.pendown()
    tr.color('light blue')
    tr.forward(100)
    tr.color('brown')
    tr.forward(200)
    tr.penup()
    tr.pendown()
    tr.color('light green')
    tr.circle(2)
    tr.color('light blue')
    tr.circle(4)
    tr.penup()
    tr.forward(20)
    tr.pendown()
    tr.circle(6)
    tr.penup()
    tr.forward(40)
    tr.pendown()
    tr.circle(8)
    tr.penup()
    tr.forward(80)
    tr.pendown()
    tr.circle(10)
    tr.penup()
    tr.forward(120)
    tr.penup()
    tr.circle(20)
    tr.color("yellow")
    tr.circle(10)
    tr.penup()
    tr.pendown()
    tr.color('white')
    tr.forward(150)
    tr.color('red')
    tr.forward(50)
    tr.color('blue')
    tr.begin_fill()
    tr.penup()
    tr.home()
    move=move+1
tr.penup()
tr.forward(50)

            
